In [ ]:
#Task 1
#Class Code
class Student:
  ID = 0
  def __init__(self,name,department,age,CGPA):
    self.name = name
    self.department = department
    self.age = age
    self.CGPA = CGPA
    Student.ID+=1

  def showDetails(self):
    print(f"ID: {Student.ID}")
    print(f"Name: {self.name}")
    print(f"Department: {self.department}")
    print(f"Age: {self.age}")
    print(f"CGPA: {self.CGPA}")

  @classmethod
  def from_String(cls,string):
    name,department,age,CGPA = string.split("-")
    cls = Student(name,department,age,CGPA)
    return cls

#Driver Code
#Write your code here for subtasks 1-6.
s1 = Student("Samin", "CSE", 21, 3.91)
s1.showDetails()
print("-----------------------")
s2 = Student("Fahim", "ECE", 21, 3.85)
s2.showDetails()
print("-----------------------")
s3 = Student("Tahura", "EEE", 22, 3.01)
s3.showDetails()
print("-----------------------")
s4 = Student.from_String("Sumaiya-BBA-23-3.96")
s4.showDetails()

print()
# Write the answer of subtask 5 here
print("Class variable: shared, Instance variable: unique")
# Write the answer of subtask 6 here
print("Instance method: accesses instance attributes, Class method: accesses class attributes")

ID: 1
Name: Samin
Department: CSE
Age: 21
CGPA: 3.91
-----------------------
ID: 2
Name: Fahim
Department: ECE
Age: 21
CGPA: 3.85
-----------------------
ID: 3
Name: Tahura
Department: EEE
Age: 22
CGPA: 3.01
-----------------------
ID: 4
Name: Sumaiya
Department: BBA
Age: 23
CGPA: 3.96

Class variable: shared, Instance variable: unique
Instance method: accesses instance attributes, Class method: accesses class attributes

In [ ]:
#Task 2
#Class Code
class Passenger:
  count = 0
  def __init__(self,name,fare= 450):
    self.name = name
    self.fare = fare
    self.__weight = 0
    Passenger.count+=1

  def set_bag_weight(self,weight):
    self.__weight = weight
    if self.__weight>20:
      if self.__weight<50:
        self.fare+=50
      else:
        self.fare+=100

  def printDetail(self):
    print(f"Name: {self.name}")
    print(f"Fare: {self.fare} taka")

#Driver Code
print("Total Passenger:", Passenger.count)
p1 = Passenger("Jack")
p1.set_bag_weight(90)
p2 = Passenger("Carol")
p2.set_bag_weight(10)
p3 = Passenger("Mike")
p3.set_bag_weight(25)
print("=========================")
p1.printDetail()
print("=========================")
p2.printDetail()
print("=========================")
p3.printDetail()
print("=========================")
print("Total Passenger:", Passenger.count)

Total Passenger: 0
=========================
Name: Jack
Fare: 550 taka
=========================
Name: Carol
Fare: 450 taka
=========================
Name: Mike
Fare: 500 taka
=========================
Total Passenger: 3

In [ ]:
#Task 3
#Class Code
class Travel:
  count = 0
  def __init__(self,start,end):
    self.__start = start
    self.__end = end
    self.__time = 1

  def set_source(self,location):
    self.__start = location
  def set_destination(self,location):
    self.__end = location
  def set_time(self,hours):
    self.__time = hours

  def display_travel_info(self):
    Travel.count+=1
    return f"Source: {self.__start}\nDestination: {self.__end}\nFlight Time: {self.__time}:00"

#Driver Code
print("No. of Traveller =", Travel.count)
print("=======================")
t1 = Travel("Dhaka","India")
print(t1.display_travel_info())
print("=======================")
t2 = Travel("Kuala Lampur","Dhaka")
t2.set_time(23)
print(t2.display_travel_info())
print("=======================")
t3 = Travel("Dhaka","New_Zealand")
t3.set_time(15)
t3.set_destination("Germany")
print(t3.display_travel_info())
print("=======================")
t4 = Travel("Dhaka","India")
t4.set_time(9)
t4.set_source("Malaysia")
t4.set_destination("Canada")
print(t4.display_travel_info())
print("=======================")
print("No. of Traveller =", Travel.count)

No. of Traveller = 0
=======================
Source: Dhaka
Destination: India
Flight Time: 1:00
=======================
Source: Kuala Lampur
Destination: Dhaka
Flight Time: 23:00
=======================
Source: Dhaka
Destination: Germany
Flight Time: 15:00
=======================
Source: Malaysia
Destination: Canada
Flight Time: 9:00
=======================
No. of Traveller = 4

In [ ]:
#Task 4
#Class Code
class NikeBangladesh:
  branches = []
  stock = {'Air Jordan':0,
           'Cortez':0,
           'Zoom Kobe':0}
  sold = 0
  def __init__(self,name):
    self.name = name
    self.stock = {'Air Jordan':0,
           'Cortez':0,
           'Zoom Kobe':0}
    self.sold = 0
    NikeBangladesh.branches.append(self.name)
  def restockProducts(self,stock):
    for key,value in stock.items():
      NikeBangladesh.stock[key]+=value
      self.stock[key]+=value
  def productSold(self,products):
    for key,value in products.items():
      self.stock[key]-=value
      NikeBangladesh.stock[key]-=value
      self.sold+=value
      NikeBangladesh.sold+=value
  def details(self):
    print(f"Nike {self.name} outlet:")
    print(f"Products Currently Stocked: {self.stock}")
    print(f"Sold: {self.sold}")
  @classmethod
  def status(cls):
    print(f"Nike Bangladesh Status:")
    print(f"Branches Opened: {NikeBangladesh.branches}")
    print(f"Currently Stocked: {NikeBangladesh.stock}")
    print(f"Sold: {NikeBangladesh.sold}")

#Driver Code
print("xxxxxxxxxxxxxx1xxxxxxxxxxxxxxxx")
NikeBangladesh.status()
dhaka = NikeBangladesh("Dhaka Banani")
chittagong = NikeBangladesh("Chittagong GEC")
print("xxxxxxxxxxxxxx2xxxxxxxxxxxxxxxx")
dhaka.details()
print("xxxxxxxxxxxxxx3xxxxxxxxxxxxxxxx")
chittagong.details()
print("xxxxxxxxxxxxxx4xxxxxxxxxxxxxxxx")
dhaka.restockProducts(
{"Air Jordan":1200,"Cortez":200,"Zoom Kobe":200})
chittagong.restockProducts(
{"Air Jordan":1000,"Cortez":250,"Zoom Kobe":100})
print("xxxxxxxxxxxxxx5xxxxxxxxxxxxxxxx")
NikeBangladesh.status()
print("xxxxxxxxxxxxxx6xxxxxxxxxxxxxxxx")
dhaka.productSold({"Air Jordan":760,"Cortez":90})
chittagong.productSold({"Air Jordan":520,"Zoom Kobe":70})
print("xxxxxxxxxxxxxx7xxxxxxxxxxxxxxxx")
NikeBangladesh.status()

xxxxxxxxxxxxxx1xxxxxxxxxxxxxxxx
Nike Bangladesh Status:
Branches Opened: []
Currently Stocked: {'Air Jordan': 0, 'Cortez': 0, 'Zoom Kobe': 0}
Sold: 0
xxxxxxxxxxxxxx2xxxxxxxxxxxxxxxx
Nike Dhaka Banani outlet:
Products Currently Stocked: {'Air Jordan': 0, 'Cortez': 0, 'Zoom Kobe': 0}
Sold: 0
xxxxxxxxxxxxxx3xxxxxxxxxxxxxxxx
Nike Chittagong GEC outlet:
Products Currently Stocked: {'Air Jordan': 0, 'Cortez': 0, 'Zoom Kobe': 0}
Sold: 0
xxxxxxxxxxxxxx4xxxxxxxxxxxxxxxx
xxxxxxxxxxxxxx5xxxxxxxxxxxxxxxx
Nike Bangladesh Status:
Branches Opened: ['Dhaka Banani', 'Chittagong GEC']
Currently Stocked: {'Air Jordan': 2200, 'Cortez': 450, 'Zoom Kobe': 300}
Sold: 0
xxxxxxxxxxxxxx6xxxxxxxxxxxxxxxx
xxxxxxxxxxxxxx7xxxxxxxxxxxxxxxx
Nike Bangladesh Status:
Branches Opened: ['Dhaka Banani', 'Chittagong GEC']
Currently Stocked: {'Air Jordan': 920, 'Cortez': 360, 'Zoom Kobe': 230}
Sold: 1440

In [ ]:
#Task 5
#Class Code
class Student:
  total_student = 0
  bracu_student = 0
  other_uni_student = 0

  def __init__(self,name,department,institution = "BRAC University"):
    self.name = name
    self.department = department
    self.institution = institution
    Student.total_student += 1
  def individualDetail(self):
    print(f"Name: {self.name}")
    print(f"Department: {self.department}")
    if self.institution == "BRAC University":
      Student.bracu_student +=1
    else:
      Student.other_uni_student+=1
    print(f"Institution: {self.institution}")

  @classmethod
  def createStudent(cls,name,department,institution="BRAC University"):
    return Student(name,department,institution)
  @classmethod
  def printDetails(cls):
    print(f"Total Student(s): {Student.total_student}")
    print(f"BRAC University Student(s): {Student.bracu_student}")
    print(f"Other Institution Student(s): {Student.other_uni_student}")

#Driver Code
# Write your code here

Student.printDetails()
print('#########################')

mikasa = Student('Mikasa Ackerman', "CSE")
mikasa.individualDetail()
print('------------------------------------------')
Student.printDetails()

print('========================')

harry = Student.createStudent('Harry Potter', "Defence Against Dark Arts", "Hogwarts School")
harry.individualDetail()
print('-------------------------------------------')
Student.printDetails()

print('=========================')

levi = Student.createStudent("Levi Ackerman", "CSE")
levi.individualDetail()
print('--------------------------------------------')
Student.printDetails()

Total Student(s): 0
BRAC University Student(s): 0
Other Institution Student(s): 0
#########################
Name: Mikasa Ackerman
Department: CSE
Institution: BRAC University
------------------------------------------
Total Student(s): 1
BRAC University Student(s): 1
Other Institution Student(s): 0
========================
Name: Harry Potter
Department: Defence Against Dark Arts
Institution: Hogwarts School
-------------------------------------------
Total Student(s): 2
BRAC University Student(s): 1
Other Institution Student(s): 1
=========================
Name: Levi Ackerman
Department: CSE
Institution: BRAC University
--------------------------------------------
Total Student(s): 3
BRAC University Student(s): 2
Other Institution Student(s): 1

In [13]:
#Task 6
#Class Code
class SultansDine:
  branch = 0
  sales = 0
  info = []
  def __init__(self,name):
    self.name = name
    self.sales = 0
    SultansDine.branch += 1
    SultansDine.info.append(self) #self is the location of object
  def sellQuantity(self,quantity):
    if quantity<10:
      self.sales += quantity*300
      SultansDine.sales += self.sales
    elif quantity<20:
      self.sales += quantity*350
      SultansDine.sales += self.sales
    else:
      self.sales += quantity*400
      SultansDine.sales+= self.sales
  def branchInformation(self):
    print(f"Branch Name: {self.name}")
    print(f"Branch Sell: {self.sales} Taka")
  @classmethod
  def details(cls):
    print(f"Total Number of branch(s): {SultansDine.branch}")
    print(f"Total Sell: {SultansDine.sales} Taka")
    for cls in SultansDine.info:
      print(f"Branch Name: {cls.name}, Branch Sell: {cls.sales} Taka")
      print(f"Branch Consists of total sell's: {round((cls.sales/SultansDine.sales)*100,2)}%")

#Driver Code
SultansDine.details()
print('########################')
dhanmondi = SultansDine('Dhanmondi')
dhanmondi.sellQuantity(25)
dhanmondi.branchInformation()
print('-----------------------------------------')
SultansDine.details()

print('========================')

baily_road = SultansDine('Baily Road')
baily_road.sellQuantity(15)
baily_road.branchInformation()
print('-----------------------------------------')
SultansDine.details()

print('========================')

gulshan = SultansDine('Gulshan')
gulshan.sellQuantity(9)
gulshan.branchInformation()
print('-----------------------------------------')
SultansDine.details()

Total Number of branch(s): 0
Total Sell: 0 Taka
########################
Branch Name: Dhanmondi
Branch Sell: 10000 Taka
-----------------------------------------
Total Number of branch(s): 1
Total Sell: 10000 Taka
Branch Name: Dhanmondi, Branch Sell: 10000 Taka
Branch Consists of total sell's: 100.0%
========================
Branch Name: Baily Road
Branch Sell: 5250 Taka
-----------------------------------------
Total Number of branch(s): 2
Total Sell: 15250 Taka
Branch Name: Dhanmondi, Branch Sell: 10000 Taka
Branch Consists of total sell's: 65.57%
Branch Name: Baily Road, Branch Sell: 5250 Taka
Branch Consists of total sell's: 34.43%
========================
Branch Name: Gulshan
Branch Sell: 2700 Taka
-----------------------------------------
Total Number of branch(s): 3
Total Sell: 17950 Taka
Branch Name: Dhanmondi, Branch Sell: 10000 Taka
Branch Consists of total sell's: 55.71%
Branch Name: Baily Road, Branch Sell: 5250 Taka
Branch Consists of total sell's: 29.25%
Branch Name: Gulshan, Branch Sell: 2700 Taka
Branch Consists of total sell's: 15.04%